version: '3'

services:
    nginx:
        image: nginx:1.19-alpine
        restart: on-failure
        volumes:
            - './public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - "8000:80"
        depends_on:
            - php
        networks:
            - dvd_rental
    php:
        build:
            context: ./docker/php-fmp
        volumes:
            - '.:/usr/src/app'
        depends_on:
            - db
        ports:
            - "9000:9000"
        networks:
            - dvd_rental
    db:
        container_name: db
        image: mysql:8
        command: [ "--default-authentication-plugin=mysql_native_password" ]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: RootStrongPassword
            MYSQL_DATABASE: dvd_rental
            MYSQL_USER: dvd_rental
            MYSQL_PASSWORD: StrongPassword
        networks:
            - dvd_rental
networks:
    dvd_rental:
        driver: bridge
